In [3]:
import numpy as np
print("Numpy version : " , np.__version__)

Numpy version :  2.1.3


In [4]:
marks_list = [45,60,72,88]
marks_array = np.array(marks_list)

print("List  : ", marks_list)

List  :  [45, 60, 72, 88]


In [5]:
print("Array : ", marks_array)

Array :  [45 60 72 88]


In [6]:
print("Type of list : ", type(marks_list))

Type of list :  <class 'list'>


In [7]:
print("Type of array : ", type(marks_array))

Type of array :  <class 'numpy.ndarray'>


In [8]:
print("Type of data in array : " , marks_array.dtype)

Type of data in array :  int64


## Lab Task 2A (5 minutes):
- Create a list of 5 temperatures in Celsius (for example [22, 25, 28, 30, 27]).
-  Convert it to a NumPy array using np.array() and print it.
-  Print the type of the array (should show numpy.ndarray).

In [9]:
temperatures_list = [22,25,28,30,27]

temperatures_array = np.array(temperatures_list)

print("Temperatures Array : " ,temperatures_array)
print("Type of array : " , type(temperatures_array))

Temperatures Array :  [22 25 28 30 27]
Type of array :  <class 'numpy.ndarray'>


In [10]:
a = np.arange(0 , 10 , 2)
print("Arange array : " , a)

Arange array :  [0 2 4 6 8]


In [11]:
b = np.linspace(0 ,1 ,5)
print(f"Linspace array : , {b} " )

Linspace array : , [0.   0.25 0.5  0.75 1.  ] 


## Lab Task 2B (10 minutes):
- Create an array of all even numbers from 2 to 20 using np.arange.
- Create an array of 6 values between 5 and 10 using np.linspace.
- In your notebook, write one possible AI use-case for each (e.g., threshold ranges, time steps, feature ranges).

In [12]:
evens_array = np.arange(2,21,2)
print("Evan numbers array : ", evens_array)

arr = np.linspace(5,10, 6)
print("\nArray of 6 values between 5 and 10 : " , arr)



Evan numbers array :  [ 2  4  6  8 10 12 14 16 18 20]

Array of 6 values between 5 and 10 :  [ 5.  6.  7.  8.  9. 10.]


In [13]:
zeros_arr = np.zeros((3,3))
ones_arr = np.ones((2,4))
rand_arr = np.random.rand(2,3)

print("Zeros : \n ", zeros_arr)
print("\nOnes : \n" , ones_arr)
print("\nRandom : \n" , rand_arr)

Zeros : 
  [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Ones : 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Random : 
 [[0.4938332  0.31823569 0.40703374]
 [0.81484209 0.88455271 0.31026016]]


## Lab Task 2C (10 minutes):
- Create a 4x4 zeros array and imagine it as “empty feature matrix for 4 students and 4 features”.
- Create a 3x2 ones array and think of it as “default feature = 1” for some binary flags.
- Create a 5-element random array. Print it and write: “This could be random initial weights”.

In [14]:
zeros_arr = np.zeros((4,4))
ones_arr = np.ones((3 , 2))
np.random.seed(42)
rand_arr = np.random.rand(5)

print("Zeros : \n ", zeros_arr)
print("\nOnes : \n" , ones_arr)
print("\nRandom Array : \n" , rand_arr)

Zeros : 
  [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones : 
 [[1. 1.]
 [1. 1.]
 [1. 1.]]

Random Array : 
 [0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]


In [15]:
arr = np.array([10,20,30,40,50])

print(arr[0])
print(arr[2])
print(arr[-1])

10
30
50


In [16]:
print(arr[1:4])

[20 30 40]


In [17]:
print(arr[:3])

[10 20 30]


In [18]:
print(arr[:2])

[10 20]


In [19]:
print(arr[::2])

[10 30 50]


## Lab Task 3A (10 minutes):
- Create a = np.array([5, 10, 15, 20, 25, 30]).
- Print:
  - First element using a[0].
  - Last two elements using slicing.
  - Every second element (step = 2).
- In notebook, write: “What does a[1:4] give?” and check by printing.

In [20]:
a = np.array([5,10,15,20,25,30])
print("First Element : ", a[0])
print("Last two elements : " , a[-2:])
print("Every Second element step 2 : ", a[::2])

First Element :  5
Last two elements :  [25 30]
Every Second element step 2 :  [ 5 15 25]


In [21]:
print(arr[1:4])

[20 30 40]


In [22]:
m = np.array ([[1,2,3] , [4,5,6] , [7,8,9]])
print("Matrix : \n ",m)

Matrix : 
  [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [23]:
print("m[0,1] : ", m[0,1])

m[0,1] :  2


In [24]:
print("Second row  : " , m[1, 0:])

Second row  :  [4 5 6]


In [25]:
print("Third colum : " , m[: , 2])

Third colum :  [3 6 9]


In [26]:
print("Sub matrix : \n " , m[0:2 , 0:2])

Sub matrix : 
  [[1 2]
 [4 5]]


## Lab Task 3B (15 minutes):

- Create:
```
    mat = np.array([
        [10, 20, 30, 40],
        [50, 60, 70, 80],
        [90, 100, 110, 120]
    ])
```              

- Print:
 - Element at row 2, column 1.
 - Entire second row.
 - Entire last column.
 - Sub-matrix of first 2 rows and first 3 columns.

- In notebook, explain: “Row = sample, Column = feature” using this matrix as example.

In [27]:
mat = np.array([[10,20,30,40] , [50,60,70,80] , [90,100,110,120]])
print("Element at row 2, column 1 : ", mat[1,0])

Element at row 2, column 1 :  50


In [28]:
print("Entire second row : ", mat[1 , 0:])

Entire second row :  [50 60 70 80]


In [29]:
print("Entire last column : ", mat[0: , -1])

Entire last column :  [ 40  80 120]


In [30]:
arr = np.array([1,2,3,4])

print("Array : ", arr)
print("arr + 10  = ", arr+10)
print("arr * 2 = " , arr*2)
print("arr ** 2 = ", arr**2)
print("arr / 2 = ",arr/2)
print("arr //2 = " ,arr//2)

Array :  [1 2 3 4]
arr + 10  =  [11 12 13 14]
arr * 2 =  [2 4 6 8]
arr ** 2 =  [ 1  4  9 16]
arr / 2 =  [0.5 1.  1.5 2. ]
arr //2 =  [0 1 1 2]


In [31]:
# Add 5 only to values < 3
new_arr = np.where(arr < 3, arr + 5, arr)

print("Updated Array (values < 3 increased by 5):", new_arr)

Updated Array (values < 3 increased by 5): [6 7 3 4]


## Lab Task 4A (10 minutes):

- Create: marks = np.array([40, 55, 63, 72, 90]).
- Increase every mark by 5 bonus marks using marks + 5.
- In notebook, write: “If marks are out of 100, what does marks / 100 represent?”

In [32]:
marks = np.array([40,55,63,72,90,100])

print("Marks : " , marks)
print("Bonus 5 marks : ", marks+5)
new_marks = np.where(marks == 100 , marks / 100 , marks)
print("If marks are out of 100, what does marks / 100 represent : ",new_marks)

Marks :  [ 40  55  63  72  90 100]
Bonus 5 marks :  [ 45  60  68  77  95 105]
If marks are out of 100, what does marks / 100 represent :  [40. 55. 63. 72. 90.  1.]


In [33]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("a + b =", a + b)    
print("a * b =", a * b)    

a + b = [5 7 9]
a * b = [ 4 10 18]


## Lab task 4B

In [34]:
x = np.array([2,4,6,8])
y = np.array([1,3,5,7])

print("x + y = ",x+y)

x + y =  [ 3  7 11 15]


In [35]:
print("x - y = ",x-y)

x - y =  [1 1 1 1]


In [36]:
print("x * y = ", x*y)

x * y =  [ 2 12 30 56]


In [37]:
data = np.array([10,20,35,40,50])

print("Min:", np.min(data))

Min: 10


In [38]:
print("Max:", np.max(data))

Max: 50


In [39]:
print("Mean:", np.mean(data))

Mean: 31.0


 ## Lab Task 4C 

In [40]:
arr = np.random.randint(0 , 101 , size = 8)

print("Min:", np.min(arr))
print("Max:", np.max(arr))
print("Average:", np.average(arr))

Min: 2
Max: 99
Average: 65.875


In [41]:
import numpy as np

values = np.array([15,16,200,17,16,400,15,18])
print("Original values : " ,values)

mean_val = np.mean(values)
std_val = np.std(values)

print("Mean:", mean_val)
print("Std: ", std_val)

cleaned = np.where(values > 100 , mean_val , values)

print("Cleaned values : " ,cleaned)

Original values :  [ 15  16 200  17  16 400  15  18]
Mean: 87.125
Std:  132.6880151897676
Cleaned values :  [15.    16.    87.125 17.    16.    87.125 15.    18.   ]


## Lab Task 5 (15–20 minutes):
- Run the code and observe the original and cleaned values.
- Change threshold from 100 to 50 and observe what changes.
- Add one more wrong value at the end (e.g., 1) and modify the code so that:
  - Values > 100 OR values < 5 are replaced by mean.
- Write 3–4 lines in notebook: “If I don’t clean data before AI model, what problems can happen?”

In [42]:
import numpy as np

values = np.array([15,16,200,17,16,400,15,18])
print("Original values : " ,values)

mean_val_1 = np.mean(values)
print("Mean:", mean_val_1)

# Change threshold from 100 to 50 and observe what changes.
cleaned2 = np.where(values > 50 , mean_val_1 , values)
print("Cleaned values  upto 50 : " ,cleaned2)

# Add one more wrong value at the end (e.g., 1)
values = np.array([15,16,200,17,16,400,15,18 , 1])

mean_val_2 = np.mean(values)
print("Mean:", mean_val_2)

#Values > 100 OR values < 5 are replaced by mean.
cleaned_3 = np.where((values > 100) | (values < 5) , mean_val_2  , values)
print("Cleaned Values > 100 OR values < 5 : " ,cleaned_3)

Original values :  [ 15  16 200  17  16 400  15  18]
Mean: 87.125
Cleaned values  upto 50 :  [15.    16.    87.125 17.    16.    87.125 15.    18.   ]
Mean: 77.55555555555556
Cleaned Values > 100 OR values < 5 :  [15.         16.         77.55555556 17.         16.         77.55555556
 15.         18.         77.55555556]


## Home Task & Short Quiz


### Home Task (To be submitted next lab)
- Create a 4x4 matrix representing marks of 4 students in 4 subjects.
- Use NumPy to:
 1. Print marks of student 2 (row 1).
 2. Print all marks of subject 3 (column 2).
 3. Find average marks of each student using np.mean(matrix, axis=1).
- Save your code and output as PDF or screenshots for submissio

In [43]:
mat = np.array([[10,20,30,40],
                [50,40,60,10],
                [10,30,45,56],
                [45,23,45,67]])

#Print marks of student 2 (row 1).
print("Marks of student 2 (row 1) = ", mat[0,1])

#Print all marks of subject 3 (column 2).
print("All marks of subject 3 (column 2) = ", mat[0: , 2])

#Find average marks of each student using np.mean(matrix, axis=1).
print("Average marks of each student : " , np.mean(mat , axis = 1))

Marks of student 2 (row 1) =  20
All marks of subject 3 (column 2) =  [30 60 45 45]
Average marks of each student :  [25.   40.   35.25 45.  ]


1. What is NumPy? Why is it important for AI? (1–2 lines)

NumPy is a Python library used for fast numerical calculations.
It is important for AI because it handles large datasets efficiently using powerful arrays and matrix operations.

2. One difference between a Python list and a NumPy array

A Python list can store mixed data types, while a NumPy array stores only one data type and performs operations much faster.

3. What does np.arange(0, 10, 2) return?

It returns even numbers from 0 to 8:
[0, 2, 4, 6, 8]

4. How do you access the element in row 2, column 3 of a matrix m?

Use indexing:
m[1, 2]
(because indexing starts from 0)

5. Predict the output:
arr = np.array([2, 4, 6, 8])
print(arr[1:3])


Output:
[4, 6]